Add better error message

diff --git a/.github/workflows/release_flow.yml b/.github/workflows/release_flow.yml
--- a/.github/workflows/release_flow.yml
+++ b/.github/workflows/release_flow.yml
@@ -29,4 +29,6 @@ jobs:
       - if: ${{ fromJSON(steps.get_latest_release.outputs.data).repository.release.isLatest}}
         run: echo "This is the latest release, i.e. we should deploy it."
       - if: ${{ !fromJSON(steps.get_latest_release.outputs.data).repository.release.isLatest}}
-        run: echo "This is not the latest release, i.e. we should not deploy it." && exit 1
+        run: |
+          echo "::error file=release_flow.yml::{This is not the latest release, i.e. we should not deploy it.}"
+          exit 1
